version: '3.8'

services:
  redis:
    image: redis:alpine
  
  mongodb:
    image: mongo

  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=FintechCluster

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password123

  app:
    build: .
    depends_on:
      - redis
      - mongodb
      - cassandra
      - neo4j
    # O PULO DO GATO:
    tty: true 
    stdin_open: true
    restart: on-failure